spring:
  autoconfigure:
    exclude: []
  application:
    name: price_monitor
  # 基本的数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/price_monitor?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

# MyBatis Plus 的配置
mybatis-plus:
  # mybatis 配置文件的路径
  # config-location: "classpath:mybatis/mybatis.config"
  # mapper 映射文件的路径，可以有多个
  mapper-locations: classpath*:/mapper/*.xml  # 如果你有 XML 的话
  type-aliases-package: org.swallow.entity      # 你的实体类包名
  configuration:
      map-underscore-to-camel-case: true